name: CI
on: [pull_request]
jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test
